apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: channel-openshift-gitops
  namespace: ns-channel-ocpgitops
  labels:
    app:  openshift-gitops-tmp
  annotations:
    apps.open-cluster-management.io/reconcile-rate: high
spec:
  type: Git
  pathname: https://github.com/sfab73/rhacm-gitops.git
